# Generated by Django 5.1.7 on 2025-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="password",
            field=models.CharField(max_length=12),
        ),
    ]
